# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
url:              https://bootstrap.7pro.ca
baseurl:          /docs/3.4
encoding:         UTF-8
exclude:
  - assets/less/

plugins:
  - jekyll-sitemap
  - kramdown-parser-gfm

# Custom vars
title:            Bootstrap
description:      "The world's most popular mobile-first and responsive front-end framework."
current_version:  3.4.3
docs_version:     3.4
repo:             https://github.com/entreprise7pro/bootstrap
sass_repo:        https://github.com/entreprise7pro/bootstrap-sass

download:
  source:         https://github.com/entreprise7pro/bootstrap/archive/v3.4.3.zip
  dist:           https://github.com/entreprise7pro/bootstrap/archive/refs/tags/v3.4.3.zip
  sass:           https://github.com/entreprise7pro/bootstrap-sass/archive/refs/tags/v3.4.3.tar.gz

blog:             https://blog.getbootstrap.com
expo:             https://expo.getbootstrap.com
themes:           https://themes.getbootstrap.com

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:            https://cdn.jsdelivr.net/gh/entreprise7pro/bootstrap@v3.4.3/dist/css/bootstrap.min.css
  css_hash:       "sha384-b6a156d707bdb74c2de7d9de7082854168702477879bc0de09049b2c54ec9863eb0d4ba6ffe095567d50dc51e72bb922"
  css_theme:      https://cdn.jsdelivr.net/gh/entreprise7pro/bootstrap@v3.4.3/dist/css/bootstrap-theme.min.css
  css_theme_hash: "sha384-81cf7fec3300565354f21a9e9bc80c442b0592402c48632668f949bcf3ffa21eec237e5edbe3f7f3d61ef63ab7fa21ef"
  js:             https://cdn.jsdelivr.net/gh/entreprise7pro/bootstrap@v3.4.3/dist/js/bootstrap.min.js
  js_hash:        "sha384-a1d7e5741edb138a10ad230c433443855e1bf32b14bee03724095c348a64b93b06306793479faf91701dd04ac94e3692"
