# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
url:              https://bootstrap.7pro.ca
baseurl:          /docs/3.4
encoding:         UTF-8
exclude:
  - assets/less/

plugins:
  - jekyll-sitemap
  - kramdown-parser-gfm

# Custom vars
title:            Bootstrap
description:      "The world's most popular mobile-first and responsive front-end framework."
current_version:  3.4.4
docs_version:     3.4
repo:             https://github.com/entreprise7pro/bootstrap
sass_repo:        https://github.com/entreprise7pro/bootstrap-sass

download:
  source:         https://github.com/entreprise7pro/bootstrap/archive/v3.4.4.zip
  dist:           https://github.com/entreprise7pro/bootstrap/archive/refs/tags/v3.4.4.zip
  sass:           https://github.com/entreprise7pro/bootstrap-sass/archive/refs/tags/v3.4.4.tar.gz

blog:             https://blog.getbootstrap.com
expo:             https://expo.getbootstrap.com
themes:           https://themes.getbootstrap.com

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:            https://cdn.jsdelivr.net/npm/entreprise7pro-bootstrap@3.4.4/dist/css/bootstrap.min.css
  css_hash:       "sha384-tqFW1we9t0wt59necIKFQWhwJHeHm8DeCQSbLFTsmGPrDUum/+CVVn1Q3FHnK7ki"
  css_theme:      https://cdn.jsdelivr.net/npm/entreprise7pro-bootstrap@3.4.4/dist/css/bootstrap-theme.min.css
  css_theme_hash: "sha384-gc9/7DMAVlNU8hqem8gMRCsFkkAsSGMmaPlJvPP/oh7sI35e2+P389Ye9jq3+iHv"
  js:             https://cdn.jsdelivr.net/npm/entreprise7pro-bootstrap@3.4.4/dist/js/bootstrap.min.js
  js_hash:        "sha384-odfldB7bE4oQrSMMQzRDhV4b8ysUvuA3JAlcNIpkuTsGMGeTR5+vkXAd0ErJTjaS"
